rust-dev 20230713
conda-forge/rust-feedstock pull request #152
Opened 2023-07-13 20:15 UTC by xhochy

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-07-27 13:05 UTC, pkgw requested changes
I think there are just a couple of typos here.

2023-07-27 13:05 UTC, pkgw commented on recipe/meta.yaml
> +    - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
Indentation problem here, it looks like.

2023-07-27 13:05 UTC, pkgw commented on recipe/meta.yaml
> +  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nigthly-x86_64-linux-android.tar.gz  # [linux and x86_64]
Typo here.

2023-08-15 08:28 UTC, xhochy commented
Merging since I adressed all comments.

2023-08-15 08:28 UTC, merged