fix: split rust-std build into unix and win version
conda-forge/rust-feedstock pull request #155
Opened 2023-07-20 06:33 UTC by ruben-arts

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) **By design the build strings will be changed.**
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

PR as a fix for the talk in #153

2023-07-20 13:43 UTC, ruben-arts commented
The CI is succeeding but I'm not sure that it works as I intended, could you check the work @pkgw @isuruf ?

2023-07-20 15:46 UTC, isuruf commented on recipe/install-rust-std-extra.bat
> +endlocal
Can you use the contents of `recipe/install-rust-std.bat` here with `s/install-rust-std.sh/install-rust-std-extra.sh/g`

2023-07-21 15:14 UTC, isuruf requested changes
You need to change lines 30-56 to change the selector from `linux and x86_64` to `(linux or win) and x86_64`

2023-07-21 17:17 UTC, isuruf commented on recipe/meta.yaml
> +        - if not exists "%LIBRARY_PREFIX%/lib/rustlib/{{ rust_std_extra }}" exit 1  # [win]
```suggestion
        - if not exist "%LIBRARY_PREFIX%/lib/rustlib/{{ rust_std_extra }}" exit 1  # [win]
```

2023-07-21 17:17 UTC, isuruf commented on recipe/meta.yaml
> +        - if not exists "%LIBRARY_PREFIX%/lib/rustlib/manifest-rust-std-{{ rust_std_extra }}" exit 1  # [win]
```suggestion
        - if not exist "%LIBRARY_PREFIX%/lib/rustlib/manifest-rust-std-{{ rust_std_extra }}" exit 1  # [win]
```

2023-07-25 15:17 UTC, merged